//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoronoiDiagApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VoronoiDiagApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1	47,096511	37,553753	142,1
        ///3	47,094867	37,530794	98,6
        ///4	47,134121	37,561340	137,8
        ///5	47,123021	37,683973	117,0
        ///7	47,100112	37,536886	51,6
        ///8	47,175113	37,694458	77,2
        ///9	47,095202	37,526828	127,0
        ///10	47,100820	37,643289	128,7
        ///14	47,108357	37,657514	117,1
        ///15	47,067355	37,485604	146,1
        ///16	47,111092	37,552492	78,6
        ///17	47,113332	37,577930	70,6
        ///18	47,103096	37,520871	109,7
        ///19	47,186687	37,513344	73,8
        ///20	47,136565	37,578637	67,2
        ///21	47,137126	37,600568	72,2
        ///24	47,152145	37,604154	74,9
        ///25	47,105069	37,51 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Coords {
            get {
                return ResourceManager.GetString("Coords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MariupolMap {
            get {
                object obj = ResourceManager.GetObject("MariupolMap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
